name: Add issues to project

on:
 workflow_call:
  secrets:
   TECH_SERVICES_GITHUB_TOKEN:
    description: 'A token passed from the caller workflow'
    required: true

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/ministryofjustice/projects/11
          TECH_SERVICES_GITHUB_TOKEN: ${{ secrets.TECH_SERVICES_GITHUB_TOKEN }}
