name: Add issues to project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  call-workflow:
    uses: ministryofjustice/cloud-operations-github-actions/.github/workflows/issue-to-project-action.yml@main
    secrets:
      github-token: ${{ secrets.TECH_SERVICES_GITHUB_TOKEN }}
