name: Add issues to project

on:
  issues:
    types:
      - opened
      - reopened
env:
 github-token: ${{ secrets.TECH_SERVICES_GITHUB_TOKEN }}

jobs:
  call-workflow:
    uses: ministryofjustice/cloud-operations/.github/workflows/issue-to-project.yml@main
    with:
      github-token: $env.github-token
    secrets: inherit
