on:
  workflow_call:
    secrets:
      JIRA_URL:
        description: 'jira URL passed from the caller workflow'
        required: true
      JIRA_EMAIL:
        description: 'email address passed from the caller workflow'
        required: true
      TECH_SERVICES_JIRA_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira Ticket
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.TECH_SERVICES_JIRA_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: TC
        issuetype: Story
        summary: |
           ${{ github.event.issue.title }} [GH#${{ github.event.issue.number }}]
        description: |
          {panel}
          *Created By:* ${{ github.event.issue.user.login }}
          [Github permalink|${{ github.event.issue.html_url }}]
          {panel}
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"

    - name: comment on github
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
          Jira Issue Reference: '${{ steps.create.outputs.issue }}'
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: '👋 Thanks for reporting!' })
