name: Add issues to project

on:
  issues:
    types:
      - opened
      - reopen

jobs:
  call-workflow:
    uses: ministryofjustice/cloud-operations/.github/workflows/issue-to-project.yml@main
    secrets: inherit
