name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  issues-to-project:
    uses: ministryofjustice/cloud-operations-github-actions/.github/workflows/issues-to-project-action.yml@main
  
