on:
  workflow_call:
    secrets:
      JIRA_SECRET:
       description: 'A token passed from the caller workflow'
       required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira Ticket
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://dsdmoj.atlassian.net/
        JIRA_USER_EMAIL: aaron.robinson1@justice.gov.uk
        JIRA_API_TOKEN: ${{ secrets.JIRA_SECRET }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: TC
        issuetype: Story
        summary: |
           ${{ github.event.issue.title }} [GH#${{ github.event.issue.number }}]
        description: |
          {panel}
          *Created By:* ${{ github.event.issue.user.login }}
          [Github permalink|${{ github.event.issue.html_url }}]
          {panel}
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
